# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationWindow_teks(object):
    def setupUi(self, InformationWindow_teks):
        InformationWindow_teks.setObjectName("InformationWindow_teks")
        InformationWindow_teks.resize(519, 374)

        self.retranslateUi(InformationWindow_teks)
        QtCore.QMetaObject.connectSlotsByName(InformationWindow_teks)

    def retranslateUi(self, InformationWindow_teks):
        _translate = QtCore.QCoreApplication.translate
        InformationWindow_teks.setWindowTitle(_translate("InformationWindow_teks", "Form"))
